// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: replay.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplayData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *DemoHeader            `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Players       []*PlayerInfo          `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	Rounds        []*RoundData           `protobuf:"bytes,3,rep,name=rounds,proto3" json:"rounds,omitempty"`
	Kills         []*KillEvent           `protobuf:"bytes,4,rep,name=kills,proto3" json:"kills,omitempty"`
	Nades         []*NadeEvent           `protobuf:"bytes,5,rep,name=nades,proto3" json:"nades,omitempty"`
	Frames        []*PlayerFrame         `protobuf:"bytes,6,rep,name=frames,proto3" json:"frames,omitempty"`
	Map           *MapData               `protobuf:"bytes,7,opt,name=map,proto3" json:"map,omitempty"`
	Flashes       []*FlashEvent          `protobuf:"bytes,8,rep,name=flashes,proto3" json:"flashes,omitempty"`
	Noises        []*NoiseEvent          `protobuf:"bytes,9,rep,name=noises,proto3" json:"noises,omitempty"`
	Bombs         []*BombEvent           `protobuf:"bytes,10,rep,name=bombs,proto3" json:"bombs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayData) Reset() {
	*x = ReplayData{}
	mi := &file_replay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayData) ProtoMessage() {}

func (x *ReplayData) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayData.ProtoReflect.Descriptor instead.
func (*ReplayData) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{0}
}

func (x *ReplayData) GetHeader() *DemoHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ReplayData) GetPlayers() []*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *ReplayData) GetRounds() []*RoundData {
	if x != nil {
		return x.Rounds
	}
	return nil
}

func (x *ReplayData) GetKills() []*KillEvent {
	if x != nil {
		return x.Kills
	}
	return nil
}

func (x *ReplayData) GetNades() []*NadeEvent {
	if x != nil {
		return x.Nades
	}
	return nil
}

func (x *ReplayData) GetFrames() []*PlayerFrame {
	if x != nil {
		return x.Frames
	}
	return nil
}

func (x *ReplayData) GetMap() *MapData {
	if x != nil {
		return x.Map
	}
	return nil
}

func (x *ReplayData) GetFlashes() []*FlashEvent {
	if x != nil {
		return x.Flashes
	}
	return nil
}

func (x *ReplayData) GetNoises() []*NoiseEvent {
	if x != nil {
		return x.Noises
	}
	return nil
}

func (x *ReplayData) GetBombs() []*BombEvent {
	if x != nil {
		return x.Bombs
	}
	return nil
}

type DemoHeader struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MapName         string                 `protobuf:"bytes,1,opt,name=map_name,json=mapName,proto3" json:"map_name,omitempty"`
	TickRate        int32                  `protobuf:"varint,2,opt,name=tick_rate,json=tickRate,proto3" json:"tick_rate,omitempty"`
	TotalTicks      int32                  `protobuf:"varint,3,opt,name=total_ticks,json=totalTicks,proto3" json:"total_ticks,omitempty"`
	ServerName      string                 `protobuf:"bytes,4,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	PlaybackTime    float32                `protobuf:"fixed32,5,opt,name=playback_time,json=playbackTime,proto3" json:"playback_time,omitempty"`
	BombTimeSeconds float32                `protobuf:"fixed32,6,opt,name=bomb_time_seconds,json=bombTimeSeconds,proto3" json:"bomb_time_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DemoHeader) Reset() {
	*x = DemoHeader{}
	mi := &file_replay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemoHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoHeader) ProtoMessage() {}

func (x *DemoHeader) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoHeader.ProtoReflect.Descriptor instead.
func (*DemoHeader) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{1}
}

func (x *DemoHeader) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *DemoHeader) GetTickRate() int32 {
	if x != nil {
		return x.TickRate
	}
	return 0
}

func (x *DemoHeader) GetTotalTicks() int32 {
	if x != nil {
		return x.TotalTicks
	}
	return 0
}

func (x *DemoHeader) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *DemoHeader) GetPlaybackTime() float32 {
	if x != nil {
		return x.PlaybackTime
	}
	return 0
}

func (x *DemoHeader) GetBombTimeSeconds() float32 {
	if x != nil {
		return x.BombTimeSeconds
	}
	return 0
}

type PlayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SteamId       uint64                 `protobuf:"varint,1,opt,name=steam_id,json=steamId,proto3" json:"steam_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Team          int32                  `protobuf:"varint,3,opt,name=team,proto3" json:"team,omitempty"`
	Kills         int32                  `protobuf:"varint,4,opt,name=kills,proto3" json:"kills,omitempty"`
	Deaths        int32                  `protobuf:"varint,5,opt,name=deaths,proto3" json:"deaths,omitempty"`
	Assists       int32                  `protobuf:"varint,6,opt,name=assists,proto3" json:"assists,omitempty"`
	Adr           float32                `protobuf:"fixed32,7,opt,name=adr,proto3" json:"adr,omitempty"`
	Kast          int32                  `protobuf:"varint,8,opt,name=kast,proto3" json:"kast,omitempty"`
	Score         int32                  `protobuf:"varint,9,opt,name=score,proto3" json:"score,omitempty"`
	TotalDamage   int32                  `protobuf:"varint,10,opt,name=total_damage,json=totalDamage,proto3" json:"total_damage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	mi := &file_replay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerInfo) GetSteamId() uint64 {
	if x != nil {
		return x.SteamId
	}
	return 0
}

func (x *PlayerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerInfo) GetTeam() int32 {
	if x != nil {
		return x.Team
	}
	return 0
}

func (x *PlayerInfo) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *PlayerInfo) GetDeaths() int32 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *PlayerInfo) GetAssists() int32 {
	if x != nil {
		return x.Assists
	}
	return 0
}

func (x *PlayerInfo) GetAdr() float32 {
	if x != nil {
		return x.Adr
	}
	return 0
}

func (x *PlayerInfo) GetKast() int32 {
	if x != nil {
		return x.Kast
	}
	return 0
}

func (x *PlayerInfo) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *PlayerInfo) GetTotalDamage() int32 {
	if x != nil {
		return x.TotalDamage
	}
	return 0
}

type RoundData struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RoundNumber       int32                  `protobuf:"varint,1,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	StartTick         int32                  `protobuf:"varint,2,opt,name=start_tick,json=startTick,proto3" json:"start_tick,omitempty"`
	EndTick           int32                  `protobuf:"varint,3,opt,name=end_tick,json=endTick,proto3" json:"end_tick,omitempty"`
	WinnerTeam        int32                  `protobuf:"varint,4,opt,name=winner_team,json=winnerTeam,proto3" json:"winner_team,omitempty"`
	WinReason         string                 `protobuf:"bytes,5,opt,name=win_reason,json=winReason,proto3" json:"win_reason,omitempty"`
	KillCount         int32                  `protobuf:"varint,6,opt,name=kill_count,json=killCount,proto3" json:"kill_count,omitempty"`
	FreezetimeEndTick int32                  `protobuf:"varint,7,opt,name=freezetime_end_tick,json=freezetimeEndTick,proto3" json:"freezetime_end_tick,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RoundData) Reset() {
	*x = RoundData{}
	mi := &file_replay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundData) ProtoMessage() {}

func (x *RoundData) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundData.ProtoReflect.Descriptor instead.
func (*RoundData) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{3}
}

func (x *RoundData) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *RoundData) GetStartTick() int32 {
	if x != nil {
		return x.StartTick
	}
	return 0
}

func (x *RoundData) GetEndTick() int32 {
	if x != nil {
		return x.EndTick
	}
	return 0
}

func (x *RoundData) GetWinnerTeam() int32 {
	if x != nil {
		return x.WinnerTeam
	}
	return 0
}

func (x *RoundData) GetWinReason() string {
	if x != nil {
		return x.WinReason
	}
	return ""
}

func (x *RoundData) GetKillCount() int32 {
	if x != nil {
		return x.KillCount
	}
	return 0
}

func (x *RoundData) GetFreezetimeEndTick() int32 {
	if x != nil {
		return x.FreezetimeEndTick
	}
	return 0
}

type KillEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Tick              int32                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	KillerSteamId     uint64                 `protobuf:"varint,2,opt,name=killer_steam_id,json=killerSteamId,proto3" json:"killer_steam_id,omitempty"`
	VictimSteamId     uint64                 `protobuf:"varint,3,opt,name=victim_steam_id,json=victimSteamId,proto3" json:"victim_steam_id,omitempty"`
	Weapon            string                 `protobuf:"bytes,4,opt,name=weapon,proto3" json:"weapon,omitempty"`
	IsHeadshot        bool                   `protobuf:"varint,5,opt,name=is_headshot,json=isHeadshot,proto3" json:"is_headshot,omitempty"`
	PenetratedObjects int32                  `protobuf:"varint,6,opt,name=penetrated_objects,json=penetratedObjects,proto3" json:"penetrated_objects,omitempty"`
	KillerX           float32                `protobuf:"fixed32,7,opt,name=killer_x,json=killerX,proto3" json:"killer_x,omitempty"`
	KillerY           float32                `protobuf:"fixed32,8,opt,name=killer_y,json=killerY,proto3" json:"killer_y,omitempty"`
	VictimX           float32                `protobuf:"fixed32,9,opt,name=victim_x,json=victimX,proto3" json:"victim_x,omitempty"`
	VictimY           float32                `protobuf:"fixed32,10,opt,name=victim_y,json=victimY,proto3" json:"victim_y,omitempty"`
	AssistedByFlash   bool                   `protobuf:"varint,11,opt,name=assisted_by_flash,json=assistedByFlash,proto3" json:"assisted_by_flash,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *KillEvent) Reset() {
	*x = KillEvent{}
	mi := &file_replay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillEvent) ProtoMessage() {}

func (x *KillEvent) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillEvent.ProtoReflect.Descriptor instead.
func (*KillEvent) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{4}
}

func (x *KillEvent) GetTick() int32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *KillEvent) GetKillerSteamId() uint64 {
	if x != nil {
		return x.KillerSteamId
	}
	return 0
}

func (x *KillEvent) GetVictimSteamId() uint64 {
	if x != nil {
		return x.VictimSteamId
	}
	return 0
}

func (x *KillEvent) GetWeapon() string {
	if x != nil {
		return x.Weapon
	}
	return ""
}

func (x *KillEvent) GetIsHeadshot() bool {
	if x != nil {
		return x.IsHeadshot
	}
	return false
}

func (x *KillEvent) GetPenetratedObjects() int32 {
	if x != nil {
		return x.PenetratedObjects
	}
	return 0
}

func (x *KillEvent) GetKillerX() float32 {
	if x != nil {
		return x.KillerX
	}
	return 0
}

func (x *KillEvent) GetKillerY() float32 {
	if x != nil {
		return x.KillerY
	}
	return 0
}

func (x *KillEvent) GetVictimX() float32 {
	if x != nil {
		return x.VictimX
	}
	return 0
}

func (x *KillEvent) GetVictimY() float32 {
	if x != nil {
		return x.VictimY
	}
	return 0
}

func (x *KillEvent) GetAssistedByFlash() bool {
	if x != nil {
		return x.AssistedByFlash
	}
	return false
}

type NadeEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Tick           int32                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	ThrowerSteamId uint64                 `protobuf:"varint,2,opt,name=thrower_steam_id,json=throwerSteamId,proto3" json:"thrower_steam_id,omitempty"`
	NadeType       string                 `protobuf:"bytes,3,opt,name=nade_type,json=nadeType,proto3" json:"nade_type,omitempty"`
	StartX         float32                `protobuf:"fixed32,4,opt,name=start_x,json=startX,proto3" json:"start_x,omitempty"`
	StartY         float32                `protobuf:"fixed32,5,opt,name=start_y,json=startY,proto3" json:"start_y,omitempty"`
	StartZ         float32                `protobuf:"fixed32,6,opt,name=start_z,json=startZ,proto3" json:"start_z,omitempty"`
	EndX           float32                `protobuf:"fixed32,7,opt,name=end_x,json=endX,proto3" json:"end_x,omitempty"`
	EndY           float32                `protobuf:"fixed32,8,opt,name=end_y,json=endY,proto3" json:"end_y,omitempty"`
	EndZ           float32                `protobuf:"fixed32,9,opt,name=end_z,json=endZ,proto3" json:"end_z,omitempty"`
	Trajectory     []*NadeTrajectoryPoint `protobuf:"bytes,10,rep,name=trajectory,proto3" json:"trajectory,omitempty"`
	DetonationTick int32                  `protobuf:"varint,11,opt,name=detonation_tick,json=detonationTick,proto3" json:"detonation_tick,omitempty"`
	FadeTick       int32                  `protobuf:"varint,12,opt,name=fade_tick,json=fadeTick,proto3" json:"fade_tick,omitempty"`
	EffectRadius   float32                `protobuf:"fixed32,13,opt,name=effect_radius,json=effectRadius,proto3" json:"effect_radius,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NadeEvent) Reset() {
	*x = NadeEvent{}
	mi := &file_replay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NadeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NadeEvent) ProtoMessage() {}

func (x *NadeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NadeEvent.ProtoReflect.Descriptor instead.
func (*NadeEvent) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{5}
}

func (x *NadeEvent) GetTick() int32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *NadeEvent) GetThrowerSteamId() uint64 {
	if x != nil {
		return x.ThrowerSteamId
	}
	return 0
}

func (x *NadeEvent) GetNadeType() string {
	if x != nil {
		return x.NadeType
	}
	return ""
}

func (x *NadeEvent) GetStartX() float32 {
	if x != nil {
		return x.StartX
	}
	return 0
}

func (x *NadeEvent) GetStartY() float32 {
	if x != nil {
		return x.StartY
	}
	return 0
}

func (x *NadeEvent) GetStartZ() float32 {
	if x != nil {
		return x.StartZ
	}
	return 0
}

func (x *NadeEvent) GetEndX() float32 {
	if x != nil {
		return x.EndX
	}
	return 0
}

func (x *NadeEvent) GetEndY() float32 {
	if x != nil {
		return x.EndY
	}
	return 0
}

func (x *NadeEvent) GetEndZ() float32 {
	if x != nil {
		return x.EndZ
	}
	return 0
}

func (x *NadeEvent) GetTrajectory() []*NadeTrajectoryPoint {
	if x != nil {
		return x.Trajectory
	}
	return nil
}

func (x *NadeEvent) GetDetonationTick() int32 {
	if x != nil {
		return x.DetonationTick
	}
	return 0
}

func (x *NadeEvent) GetFadeTick() int32 {
	if x != nil {
		return x.FadeTick
	}
	return 0
}

func (x *NadeEvent) GetEffectRadius() float32 {
	if x != nil {
		return x.EffectRadius
	}
	return 0
}

type NadeTrajectoryPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          int32                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,4,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NadeTrajectoryPoint) Reset() {
	*x = NadeTrajectoryPoint{}
	mi := &file_replay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NadeTrajectoryPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NadeTrajectoryPoint) ProtoMessage() {}

func (x *NadeTrajectoryPoint) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NadeTrajectoryPoint.ProtoReflect.Descriptor instead.
func (*NadeTrajectoryPoint) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{6}
}

func (x *NadeTrajectoryPoint) GetTick() int32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *NadeTrajectoryPoint) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *NadeTrajectoryPoint) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *NadeTrajectoryPoint) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type PlayerFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          int32                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	SteamId       uint64                 `protobuf:"varint,2,opt,name=steam_id,json=steamId,proto3" json:"steam_id,omitempty"`
	X             float32                `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,5,opt,name=z,proto3" json:"z,omitempty"`
	Yaw           float32                `protobuf:"fixed32,6,opt,name=yaw,proto3" json:"yaw,omitempty"`
	Pitch         float32                `protobuf:"fixed32,7,opt,name=pitch,proto3" json:"pitch,omitempty"`
	Health        int32                  `protobuf:"varint,8,opt,name=health,proto3" json:"health,omitempty"`
	Armor         int32                  `protobuf:"varint,9,opt,name=armor,proto3" json:"armor,omitempty"`
	Weapon        string                 `protobuf:"bytes,10,opt,name=weapon,proto3" json:"weapon,omitempty"`
	IsAlive       bool                   `protobuf:"varint,11,opt,name=is_alive,json=isAlive,proto3" json:"is_alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerFrame) Reset() {
	*x = PlayerFrame{}
	mi := &file_replay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerFrame) ProtoMessage() {}

func (x *PlayerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerFrame.ProtoReflect.Descriptor instead.
func (*PlayerFrame) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerFrame) GetTick() int32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *PlayerFrame) GetSteamId() uint64 {
	if x != nil {
		return x.SteamId
	}
	return 0
}

func (x *PlayerFrame) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerFrame) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerFrame) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *PlayerFrame) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *PlayerFrame) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *PlayerFrame) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *PlayerFrame) GetArmor() int32 {
	if x != nil {
		return x.Armor
	}
	return 0
}

func (x *PlayerFrame) GetWeapon() string {
	if x != nil {
		return x.Weapon
	}
	return ""
}

func (x *PlayerFrame) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

type FlashEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Tick            int32                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	PlayerSteamId   uint64                 `protobuf:"varint,2,opt,name=player_steam_id,json=playerSteamId,proto3" json:"player_steam_id,omitempty"`
	AttackerSteamId uint64                 `protobuf:"varint,3,opt,name=attacker_steam_id,json=attackerSteamId,proto3" json:"attacker_steam_id,omitempty"`
	DurationSeconds float32                `protobuf:"fixed32,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	EndTick         int32                  `protobuf:"varint,5,opt,name=end_tick,json=endTick,proto3" json:"end_tick,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FlashEvent) Reset() {
	*x = FlashEvent{}
	mi := &file_replay_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlashEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlashEvent) ProtoMessage() {}

func (x *FlashEvent) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlashEvent.ProtoReflect.Descriptor instead.
func (*FlashEvent) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{8}
}

func (x *FlashEvent) GetTick() int32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *FlashEvent) GetPlayerSteamId() uint64 {
	if x != nil {
		return x.PlayerSteamId
	}
	return 0
}

func (x *FlashEvent) GetAttackerSteamId() uint64 {
	if x != nil {
		return x.AttackerSteamId
	}
	return 0
}

func (x *FlashEvent) GetDurationSeconds() float32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *FlashEvent) GetEndTick() int32 {
	if x != nil {
		return x.EndTick
	}
	return 0
}

type NoiseEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          int32                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	EndTick       int32                  `protobuf:"varint,2,opt,name=end_tick,json=endTick,proto3" json:"end_tick,omitempty"`
	SteamId       uint64                 `protobuf:"varint,3,opt,name=steam_id,json=steamId,proto3" json:"steam_id,omitempty"`
	X             float32                `protobuf:"fixed32,4,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,5,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,6,opt,name=z,proto3" json:"z,omitempty"`
	Radius        float32                `protobuf:"fixed32,7,opt,name=radius,proto3" json:"radius,omitempty"`
	NoiseType     string                 `protobuf:"bytes,8,opt,name=noise_type,json=noiseType,proto3" json:"noise_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoiseEvent) Reset() {
	*x = NoiseEvent{}
	mi := &file_replay_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoiseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoiseEvent) ProtoMessage() {}

func (x *NoiseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoiseEvent.ProtoReflect.Descriptor instead.
func (*NoiseEvent) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{9}
}

func (x *NoiseEvent) GetTick() int32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *NoiseEvent) GetEndTick() int32 {
	if x != nil {
		return x.EndTick
	}
	return 0
}

func (x *NoiseEvent) GetSteamId() uint64 {
	if x != nil {
		return x.SteamId
	}
	return 0
}

func (x *NoiseEvent) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *NoiseEvent) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *NoiseEvent) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *NoiseEvent) GetRadius() float32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *NoiseEvent) GetNoiseType() string {
	if x != nil {
		return x.NoiseType
	}
	return ""
}

type BombEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          int32                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	PlayerSteamId uint64                 `protobuf:"varint,3,opt,name=player_steam_id,json=playerSteamId,proto3" json:"player_steam_id,omitempty"`
	Site          string                 `protobuf:"bytes,4,opt,name=site,proto3" json:"site,omitempty"`
	HasKit        bool                   `protobuf:"varint,5,opt,name=has_kit,json=hasKit,proto3" json:"has_kit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BombEvent) Reset() {
	*x = BombEvent{}
	mi := &file_replay_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BombEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BombEvent) ProtoMessage() {}

func (x *BombEvent) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BombEvent.ProtoReflect.Descriptor instead.
func (*BombEvent) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{10}
}

func (x *BombEvent) GetTick() int32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *BombEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *BombEvent) GetPlayerSteamId() uint64 {
	if x != nil {
		return x.PlayerSteamId
	}
	return 0
}

func (x *BombEvent) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *BombEvent) GetHasKit() bool {
	if x != nil {
		return x.HasKit
	}
	return false
}

type MapData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PosX          float64                `protobuf:"fixed64,2,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY          float64                `protobuf:"fixed64,3,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	Scale         float64                `protobuf:"fixed64,4,opt,name=scale,proto3" json:"scale,omitempty"`
	Rotate        float64                `protobuf:"fixed64,5,opt,name=rotate,proto3" json:"rotate,omitempty"`
	Zoom          float64                `protobuf:"fixed64,6,opt,name=zoom,proto3" json:"zoom,omitempty"`
	Width         int32                  `protobuf:"varint,7,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,8,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapData) Reset() {
	*x = MapData{}
	mi := &file_replay_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapData) ProtoMessage() {}

func (x *MapData) ProtoReflect() protoreflect.Message {
	mi := &file_replay_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapData.ProtoReflect.Descriptor instead.
func (*MapData) Descriptor() ([]byte, []int) {
	return file_replay_proto_rawDescGZIP(), []int{11}
}

func (x *MapData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MapData) GetPosX() float64 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *MapData) GetPosY() float64 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *MapData) GetScale() float64 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *MapData) GetRotate() float64 {
	if x != nil {
		return x.Rotate
	}
	return 0
}

func (x *MapData) GetZoom() float64 {
	if x != nil {
		return x.Zoom
	}
	return 0
}

func (x *MapData) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MapData) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_replay_proto protoreflect.FileDescriptor

const file_replay_proto_rawDesc = "" +
	"\n" +
	"\freplay.proto\x12\x06replay\"\xb6\x03\n" +
	"\n" +
	"ReplayData\x12*\n" +
	"\x06header\x18\x01 \x01(\v2\x12.replay.DemoHeaderR\x06header\x12,\n" +
	"\aplayers\x18\x02 \x03(\v2\x12.replay.PlayerInfoR\aplayers\x12)\n" +
	"\x06rounds\x18\x03 \x03(\v2\x11.replay.RoundDataR\x06rounds\x12'\n" +
	"\x05kills\x18\x04 \x03(\v2\x11.replay.KillEventR\x05kills\x12'\n" +
	"\x05nades\x18\x05 \x03(\v2\x11.replay.NadeEventR\x05nades\x12+\n" +
	"\x06frames\x18\x06 \x03(\v2\x13.replay.PlayerFrameR\x06frames\x12!\n" +
	"\x03map\x18\a \x01(\v2\x0f.replay.MapDataR\x03map\x12,\n" +
	"\aflashes\x18\b \x03(\v2\x12.replay.FlashEventR\aflashes\x12*\n" +
	"\x06noises\x18\t \x03(\v2\x12.replay.NoiseEventR\x06noises\x12'\n" +
	"\x05bombs\x18\n" +
	" \x03(\v2\x11.replay.BombEventR\x05bombs\"\xd7\x01\n" +
	"\n" +
	"DemoHeader\x12\x19\n" +
	"\bmap_name\x18\x01 \x01(\tR\amapName\x12\x1b\n" +
	"\ttick_rate\x18\x02 \x01(\x05R\btickRate\x12\x1f\n" +
	"\vtotal_ticks\x18\x03 \x01(\x05R\n" +
	"totalTicks\x12\x1f\n" +
	"\vserver_name\x18\x04 \x01(\tR\n" +
	"serverName\x12#\n" +
	"\rplayback_time\x18\x05 \x01(\x02R\fplaybackTime\x12*\n" +
	"\x11bomb_time_seconds\x18\x06 \x01(\x02R\x0fbombTimeSeconds\"\xf6\x01\n" +
	"\n" +
	"PlayerInfo\x12\x19\n" +
	"\bsteam_id\x18\x01 \x01(\x04R\asteamId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04team\x18\x03 \x01(\x05R\x04team\x12\x14\n" +
	"\x05kills\x18\x04 \x01(\x05R\x05kills\x12\x16\n" +
	"\x06deaths\x18\x05 \x01(\x05R\x06deaths\x12\x18\n" +
	"\aassists\x18\x06 \x01(\x05R\aassists\x12\x10\n" +
	"\x03adr\x18\a \x01(\x02R\x03adr\x12\x12\n" +
	"\x04kast\x18\b \x01(\x05R\x04kast\x12\x14\n" +
	"\x05score\x18\t \x01(\x05R\x05score\x12!\n" +
	"\ftotal_damage\x18\n" +
	" \x01(\x05R\vtotalDamage\"\xf7\x01\n" +
	"\tRoundData\x12!\n" +
	"\fround_number\x18\x01 \x01(\x05R\vroundNumber\x12\x1d\n" +
	"\n" +
	"start_tick\x18\x02 \x01(\x05R\tstartTick\x12\x19\n" +
	"\bend_tick\x18\x03 \x01(\x05R\aendTick\x12\x1f\n" +
	"\vwinner_team\x18\x04 \x01(\x05R\n" +
	"winnerTeam\x12\x1d\n" +
	"\n" +
	"win_reason\x18\x05 \x01(\tR\twinReason\x12\x1d\n" +
	"\n" +
	"kill_count\x18\x06 \x01(\x05R\tkillCount\x12.\n" +
	"\x13freezetime_end_tick\x18\a \x01(\x05R\x11freezetimeEndTick\"\xef\x02\n" +
	"\tKillEvent\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x05R\x04tick\x12&\n" +
	"\x0fkiller_steam_id\x18\x02 \x01(\x04R\rkillerSteamId\x12&\n" +
	"\x0fvictim_steam_id\x18\x03 \x01(\x04R\rvictimSteamId\x12\x16\n" +
	"\x06weapon\x18\x04 \x01(\tR\x06weapon\x12\x1f\n" +
	"\vis_headshot\x18\x05 \x01(\bR\n" +
	"isHeadshot\x12-\n" +
	"\x12penetrated_objects\x18\x06 \x01(\x05R\x11penetratedObjects\x12\x19\n" +
	"\bkiller_x\x18\a \x01(\x02R\akillerX\x12\x19\n" +
	"\bkiller_y\x18\b \x01(\x02R\akillerY\x12\x19\n" +
	"\bvictim_x\x18\t \x01(\x02R\avictimX\x12\x19\n" +
	"\bvictim_y\x18\n" +
	" \x01(\x02R\avictimY\x12*\n" +
	"\x11assisted_by_flash\x18\v \x01(\bR\x0fassistedByFlash\"\x98\x03\n" +
	"\tNadeEvent\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x05R\x04tick\x12(\n" +
	"\x10thrower_steam_id\x18\x02 \x01(\x04R\x0ethrowerSteamId\x12\x1b\n" +
	"\tnade_type\x18\x03 \x01(\tR\bnadeType\x12\x17\n" +
	"\astart_x\x18\x04 \x01(\x02R\x06startX\x12\x17\n" +
	"\astart_y\x18\x05 \x01(\x02R\x06startY\x12\x17\n" +
	"\astart_z\x18\x06 \x01(\x02R\x06startZ\x12\x13\n" +
	"\x05end_x\x18\a \x01(\x02R\x04endX\x12\x13\n" +
	"\x05end_y\x18\b \x01(\x02R\x04endY\x12\x13\n" +
	"\x05end_z\x18\t \x01(\x02R\x04endZ\x12;\n" +
	"\n" +
	"trajectory\x18\n" +
	" \x03(\v2\x1b.replay.NadeTrajectoryPointR\n" +
	"trajectory\x12'\n" +
	"\x0fdetonation_tick\x18\v \x01(\x05R\x0edetonationTick\x12\x1b\n" +
	"\tfade_tick\x18\f \x01(\x05R\bfadeTick\x12#\n" +
	"\reffect_radius\x18\r \x01(\x02R\feffectRadius\"S\n" +
	"\x13NadeTrajectoryPoint\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x05R\x04tick\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x04 \x01(\x02R\x01z\"\xef\x01\n" +
	"\vPlayerFrame\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x05R\x04tick\x12\x19\n" +
	"\bsteam_id\x18\x02 \x01(\x04R\asteamId\x12\f\n" +
	"\x01x\x18\x03 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x05 \x01(\x02R\x01z\x12\x10\n" +
	"\x03yaw\x18\x06 \x01(\x02R\x03yaw\x12\x14\n" +
	"\x05pitch\x18\a \x01(\x02R\x05pitch\x12\x16\n" +
	"\x06health\x18\b \x01(\x05R\x06health\x12\x14\n" +
	"\x05armor\x18\t \x01(\x05R\x05armor\x12\x16\n" +
	"\x06weapon\x18\n" +
	" \x01(\tR\x06weapon\x12\x19\n" +
	"\bis_alive\x18\v \x01(\bR\aisAlive\"\xba\x01\n" +
	"\n" +
	"FlashEvent\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x05R\x04tick\x12&\n" +
	"\x0fplayer_steam_id\x18\x02 \x01(\x04R\rplayerSteamId\x12*\n" +
	"\x11attacker_steam_id\x18\x03 \x01(\x04R\x0fattackerSteamId\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\x02R\x0fdurationSeconds\x12\x19\n" +
	"\bend_tick\x18\x05 \x01(\x05R\aendTick\"\xb7\x01\n" +
	"\n" +
	"NoiseEvent\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x05R\x04tick\x12\x19\n" +
	"\bend_tick\x18\x02 \x01(\x05R\aendTick\x12\x19\n" +
	"\bsteam_id\x18\x03 \x01(\x04R\asteamId\x12\f\n" +
	"\x01x\x18\x04 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x06 \x01(\x02R\x01z\x12\x16\n" +
	"\x06radius\x18\a \x01(\x02R\x06radius\x12\x1d\n" +
	"\n" +
	"noise_type\x18\b \x01(\tR\tnoiseType\"\x93\x01\n" +
	"\tBombEvent\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x05R\x04tick\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12&\n" +
	"\x0fplayer_steam_id\x18\x03 \x01(\x04R\rplayerSteamId\x12\x12\n" +
	"\x04site\x18\x04 \x01(\tR\x04site\x12\x17\n" +
	"\ahas_kit\x18\x05 \x01(\bR\x06hasKit\"\xb7\x01\n" +
	"\aMapData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x13\n" +
	"\x05pos_x\x18\x02 \x01(\x01R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\x03 \x01(\x01R\x04posY\x12\x14\n" +
	"\x05scale\x18\x04 \x01(\x01R\x05scale\x12\x16\n" +
	"\x06rotate\x18\x05 \x01(\x01R\x06rotate\x12\x12\n" +
	"\x04zoom\x18\x06 \x01(\x01R\x04zoom\x12\x14\n" +
	"\x05width\x18\a \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\b \x01(\x05R\x06heightB8Z6github.com/yourname/cs2-replay-viewer/backend/protobufb\x06proto3"

var (
	file_replay_proto_rawDescOnce sync.Once
	file_replay_proto_rawDescData []byte
)

func file_replay_proto_rawDescGZIP() []byte {
	file_replay_proto_rawDescOnce.Do(func() {
		file_replay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_replay_proto_rawDesc), len(file_replay_proto_rawDesc)))
	})
	return file_replay_proto_rawDescData
}

var file_replay_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_replay_proto_goTypes = []any{
	(*ReplayData)(nil),          // 0: replay.ReplayData
	(*DemoHeader)(nil),          // 1: replay.DemoHeader
	(*PlayerInfo)(nil),          // 2: replay.PlayerInfo
	(*RoundData)(nil),           // 3: replay.RoundData
	(*KillEvent)(nil),           // 4: replay.KillEvent
	(*NadeEvent)(nil),           // 5: replay.NadeEvent
	(*NadeTrajectoryPoint)(nil), // 6: replay.NadeTrajectoryPoint
	(*PlayerFrame)(nil),         // 7: replay.PlayerFrame
	(*FlashEvent)(nil),          // 8: replay.FlashEvent
	(*NoiseEvent)(nil),          // 9: replay.NoiseEvent
	(*BombEvent)(nil),           // 10: replay.BombEvent
	(*MapData)(nil),             // 11: replay.MapData
}
var file_replay_proto_depIdxs = []int32{
	1,  // 0: replay.ReplayData.header:type_name -> replay.DemoHeader
	2,  // 1: replay.ReplayData.players:type_name -> replay.PlayerInfo
	3,  // 2: replay.ReplayData.rounds:type_name -> replay.RoundData
	4,  // 3: replay.ReplayData.kills:type_name -> replay.KillEvent
	5,  // 4: replay.ReplayData.nades:type_name -> replay.NadeEvent
	7,  // 5: replay.ReplayData.frames:type_name -> replay.PlayerFrame
	11, // 6: replay.ReplayData.map:type_name -> replay.MapData
	8,  // 7: replay.ReplayData.flashes:type_name -> replay.FlashEvent
	9,  // 8: replay.ReplayData.noises:type_name -> replay.NoiseEvent
	10, // 9: replay.ReplayData.bombs:type_name -> replay.BombEvent
	6,  // 10: replay.NadeEvent.trajectory:type_name -> replay.NadeTrajectoryPoint
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_replay_proto_init() }
func file_replay_proto_init() {
	if File_replay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_replay_proto_rawDesc), len(file_replay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_replay_proto_goTypes,
		DependencyIndexes: file_replay_proto_depIdxs,
		MessageInfos:      file_replay_proto_msgTypes,
	}.Build()
	File_replay_proto = out.File
	file_replay_proto_goTypes = nil
	file_replay_proto_depIdxs = nil
}
